In [1]:
from sklearn.datasets import load_iris

iris = load_iris()

In [2]:
import pandas as pd

df = pd.DataFrame(
    data=iris['data'],
    columns=iris['feature_names']
)

df['품종'] = iris['target']

In [3]:
df['품종2'] = df['품종'].apply(lambda i: iris['target_names'][i])

In [4]:
df

sepal length (cm)  sepal width (cm)  ...  품종        품종2
0                  5.1               3.5  ...   0     setosa
1                  4.9               3.0  ...   0     setosa
2                  4.7               3.2  ...   0     setosa
3                  4.6               3.1  ...   0     setosa
4                  5.0               3.6  ...   0     setosa
..                 ...               ...  ...  ..        ...
145                6.7               3.0  ...   2  virginica
146                6.3               2.5  ...   2  virginica
147                6.5               3.0  ...   2  virginica
148                6.2               3.4  ...   2  virginica
149                5.9               3.0  ...   2  virginica

[150 rows x 6 columns]

In [5]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

In [6]:
model.fit(iris['data'], iris['target'])

DecisionTreeClassifier()

In [7]:
import numpy as np

new_data = np.array([
    [5, 3.5, 1.4, 0.25], 
    [2, 2.2, 5.3, 2.2], 
    [1.2, 5, 3.2, 7.6]
])

In [9]:
pred = model.predict(new_data)
print(pred)
print(iris['target_names'][pred])

[0 2 1]
['setosa' 'virginica' 'versicolor']


In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    iris['data'],
    iris['target'],
    test_size=0.2,
    stratify=iris['target'],
    # shuffle=True
)

In [21]:
print(iris['data'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
model2 = DecisionTreeClassifier()

model2.fit(x_train, y_train)

pred_test = model2.predict(x_test)

In [23]:
pred_test

array([1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1,
       2, 1, 0, 1, 1, 0, 0, 0])

In [24]:
from sklearn.metrics import accuracy_score

result = accuracy_score(y_test, pred_test)
print("정확도:", result)

정확도: 0.9


In [15]:
print(y_test)

[1 0 0 1 1 2 1 0 2 1 1 0 2 0 2 1 1 2 2 0 1 0 2 2 0 2 1 2 0 0]


In [53]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X.shape, y.shape

((150, 4), (150,))

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_tesy = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=0
)

X_train.shape, X_test.shape

((120, 4), (30, 4))

In [55]:
import numpy as np
np.unique([1, 1, 2, 1, 2], return_counts=True)

(array([1, 2]), array([3, 2]))

In [56]:
np.unique(y, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [57]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, 
    test_size=0.2,
    stratify=y_train,
    random_state=0)

X_train.shape, X_test.shape, X_val.shape

((96, 4), (30, 4), (24, 4))

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

max_depth = 4 # 하이퍼 파라미터. 이 값 설정에 따라 모델 성능이 바뀜.
tree = DecisionTreeClassifier(max_depth=max_depth, random_state=0) # 모델 생성

tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=0)

In [59]:
pred_train = tree.predict(X_train)
pred_val = tree.predict(X_val)

In [60]:
train_acc = accuracy_score(y_train, pred_train)
val_acc = accuracy_score(y_val, pred_val)

In [61]:
print(f"max_depth: {max_depth}")
print("Train accuracy:", train_acc)
print("Validation accuracy:", val_acc)

max_depth: 4
Train accuracy: 1.0
Validation accuracy: 1.0


In [62]:
pred = model.predict(X_test)
test_acc = accuracy_score(y_test, pred)
print("최종 평가결과:", test_acc)

최종 평가결과: 0.36666666666666664


In [64]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/boston_dataset.csv')
print(df.shape)
df.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [65]:
y = df['MEDV'].values
x = df.drop(columns='MEDV').values

In [66]:
x.shape, y.shape

((506, 13), (506,))

In [68]:
x[:3]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [69]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

In [ ]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5) # k=5 -> 8:2

gen = kfold.split(x)

In [70]:
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

mse_list = []
kfold = KFold(n_splits=5)
gen = kfold.split(X)

In [72]:
for train_idx, test_idx in gen:
    X_train, y_train = X[train_idx], y[train_idx]
    X_test, y_test = X[test_idx], y[test_idx]

    model = DecisionTreeRegressor(max_depth=2, random_state=0)

    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    mse = mean_squared_error(y_test, pred)
    mse_list.append(mse)

In [73]:
mse_list

[36.95804562466198, 20.028694351639427, 43.37290768506509, 24.05251146300498]